# Page view
type PV @collection(name: "pv") {
  url: String!
  title: String!

  browserName: String!
  browserVersion: String!

  osName: String!
  osVersion: String!

  createdAt: String!
}

type Query {
  allPV: [PV!]! @index(name: "all_pv")
}
